---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: event-service-demo
  name: event-service-demo
  namespace: default
spec:
  ports:
    - port: 9292
      protocol: TCP
      targetPort: 9292
  selector:
    service: event-service-demo
  type: NodePort